CREATE TABLE PrimaryMuscles(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
PrimaryMuscleName NVARCHAR(50) NOT NULL,
);

CREATE TABLE SecondaryMuscles(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
SecondaryMuscleName NVARCHAR(50) NOT NULL,
);

CREATE TABLE Exercises(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ExerciseName NVARCHAR(50) NOT NULL,
Category NVARCHAR(50) NOT NULL,
Equipment NVARCHAR(50) NOT NULL,
);

CREATE TABLE PrimaryMusclesExercises(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
PrimaryMuscleId INT NOT NULL FOREIGN KEY REFERENCES PrimaryMuscles(ID),
ExerciseId INT NOT NULL FOREIGN KEY REFERENCES Exercises(ID)
);

CREATE TABLE SecondaryMusclesExercises(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
SecondaryMuscleId INT NOT NULL FOREIGN KEY REFERENCES SecondaryMuscles(ID),
ExerciseId INT NOT NULL FOREIGN KEY REFERENCES Exercises(ID)
);

CREATE TABLE WorkoutPlans(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
WorkoutPlanName NVARCHAR(50) NOT NULL,
TimesPerWeek INT NOT NULL
);

CREATE TABLE Athletes(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
AthleteName NVARCHAR(50) NOT NULL,
WorkoutPlanId INT NOT NULL FOREIGN KEY REFERENCES WorkoutPlans(ID) ON DELETE Cascade,
);

CREATE TABLE WorkoutRoutines(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
RoutineName NVARCHAR(50) NOT NULL,
WorkoutPlanId INT NOT NULL FOREIGN KEY REFERENCES WorkoutPlans(ID) ON DELETE Cascade,
);

CREATE TABLE CompletedRoutines(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
AthleteId INT NOT NULL FOREIGN KEY REFERENCES Athletes(ID),
WorkoutRoutineId INT NOT NULL FOREIGN KEY REFERENCES WorkoutRoutines(ID)
);

CREATE TABLE Sets(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Weight INT NOT NULL,
NumOfReps INT NOT NULL,
WorkoutRoutineId INT NOT NULL FOREIGN KEY REFERENCES WorkoutRoutines(ID),
ExerciseId INT NOT NULL FOREIGN KEY REFERENCES Exercises(ID) ON DELETE Cascade
);

